<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ibex">

    <xacro:property name="base_length" value="0.9" />
    <xacro:property name="base_width" value="0.6" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_thickness" value="0.05" />
    <xacro:property name="wheel_y_span" value="${(base_width + wheel_thickness) / 2.0}" />
    <xacro:property name="wheel_axle_x_offset" value="${base_length / 4.0}" />
    <xacro:property name="chassis_mass" value="5.0" /> 
    <xacro:property name="wheel_mass" value="0.5" />

    <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0" />
    </material>
    
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>

    <link name="base_footprint" />

    <link name="base_link">
        <inertial>
            <mass value="${chassis_mass}" />
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <inertia ixx="${(chassis_mass/12.0) * (base_height*base_height + base_width*base_width)}" 
                     ixy="0.0" 
                     ixz="0.0" 
                     iyy="${(chassis_mass/12.0) * (base_length*base_length + base_height*base_height)}" 
                     iyz="0.0" 
                     izz="${(chassis_mass/12.0) * (base_length*base_length + base_width*base_width)}" />
        </inertial>
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
    </link>

    <xacro:macro name="wheel_macro" params="name_prefix x_offset y_offset">
        <link name="${name_prefix}_wheel_link">
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" 
                        ixy="0.0" ixz="0.0" 
                        iyy="${(wheel_mass/2.0) * (wheel_radius*wheel_radius)}" 
                        iyz="0.0" 
                        izz="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" />
        </inertial>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> 
            <material name="black" />
        </visual>
        <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> 
            </collision>
    </link>

            <joint name="${name_prefix}_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="${name_prefix}_wheel_link" />
        <origin xyz="${x_offset} ${y_offset} ${base_height / 2.0}" rpy="0 0 0" />
                    <axis xyz="0 1 0" />
    </joint>
    </xacro:macro>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius - (base_height / 2.0)}" rpy="0 0 0"/>
    </joint>

        <link name="imu_link">
        <inertial>
            <origin xyz="-0.00552433659106688 0.000168210391520346 0.000514000497342681" rpy="0 0 0" />
            <mass value="0.000528415362211671" />
            <inertia ixx="1.46176048428261E-08" ixy="1.40015117949421E-10" ixz="-1.99633872937403E-12"
                    iyy="8.59662482954888E-09" iyz="7.52375112767959E-12"
                    izz="2.30279421279312E-08" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.1 0.05"/>
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.1 0.05"/>
            </geometry>
        </collision>
    </link>
      
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0.0698986241758014" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="imu_link" />
        <axis xyz="0 0 0" />
    </joint>

    <link name="laser_link">
        <inertial>
            <origin xyz="-0.011945780406062 -0.000381929217680526 -0.0170649378129477" rpy="0 0 0" />
            <mass value="0.073084435549317" />
            <inertia ixx="1.96074931730795E-05" ixy="-3.62091076640009E-07" ixz="4.28230084046735E-07"
                    iyy="2.40983835136327E-05" iyz="1.50180909250652E-08"
                    izz="4.14184164228595E-05" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <cylinder radius="0.035" length="0.05"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <cylinder radius="0.035" length="0.05"/>
            </geometry>
        </collision>
    </link>

    <joint name="laser_joint" type="fixed">
        <origin xyz="-0.0050526 -0.0023221 0.1208" rpy="0 0 3.14" />
        <parent link="base_link" />
        <child link="laser_link" />
        <axis xyz="0 0 0" />
    </joint>

    <xacro:wheel_macro name_prefix="rear_right" 
                        x_offset="${-wheel_axle_x_offset}" 
                        y_offset="${-wheel_y_span}" />

    <xacro:wheel_macro name_prefix="rear_left" 
                        x_offset="${-wheel_axle_x_offset}" 
                        y_offset="${wheel_y_span}" />
    
        <xacro:wheel_macro name_prefix="front_right" 
                        x_offset="${wheel_axle_x_offset}" 
                        y_offset="${-wheel_y_span}" />

    <xacro:wheel_macro name_prefix="front_left" 
                        x_offset="${wheel_axle_x_offset}" 
                        y_offset="${wheel_y_span}" />

</robot>